version: '3.8'
services:
  mongodb:
    image: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - ./.data/mongodb:/data/db
      - ./migration:/migration
    ports:
      - $MONGO_PORT:$MONGO_PORT
  api:
    image: "node:18.3.0"
    depends_on: ["mongodb"]
    working_dir: /app/api
    command: bash -c "npm i && npm run start"
    env_file:
      - .env
    volumes:
      - ./api:/app/api
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - $APP_PORT:$APP_PORT
  web:
    image: "node:18.3.0"
    depends_on: ["api"]
    working_dir: /app/web
    command: bash -c "npm i && npm run dev"
    volumes:
      - "./web:/app/web"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    expose: ["3000"]
    ports: ["3000:3000"]